### ISSUE TITLE
requirements, other things

### ISSUE THREAD

**Issue by ClashSAN** [DiBianoR/Prompt_Enhancer#1]
this is gpt2 (small)sized? How much (minimum amount)vram is needed for speedy prompt generation?

**Comment by DiBianoR** [comment]
Currently GPT-Neo-125M parameter version; that's probably overkill but I wanted the best one that within a couple seconds on my computer. I looked at the vram usage... it used ~11.3 for the first generate(), then just kept filling more of my 24 as long as it was available. So... maybe 12 GB? Not really sure though. I also got it to work with the GPT-Neo-1.3B parameter but it was a little slow; I should probably make a smaller version as well.

**Comment by ClashSAN** [comment]
Wow, I didn't expect 12gb vram.. 
I was playing with the 6B Kobold AI text model (dev version) on a 4gb card. It's like 1 word every 2 seconds.
There's also https://github.com/TimDettmers/bitsandbytes 
demo: https://www.youtube.com/watch?v=lI3bZzsQcjs

With Kobold's dev repo https://github.com/henk717/KoboldAI I think they utilize the cpu in addition with the card for faster processing (I am not aware of the details)
